org: bmatias
app: tennis-trainer
service: amber-framework

plugins:
  - serverless-offline

provider:
  profile: tennis-dev
  name: aws
  runtime: nodejs8.10
  memorySize: 2048
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}
  timeout: 30

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  app:
    handler: src/app.serverless
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

  # s3Bucket:
  #   handler: src/app.s3StreamsHandler
  #   events:
  #     - s3:
  #         bucket: ${file(env.yml):dev.AWS_S3_BUCKET}
  #         event: s3:ObjectCreated:*
  #         existing: true